### ISSUE TITLE
Can't send funds from the safe on a private network

### ISSUE THREAD

**Issue by soragXYZ** [gnosis/safe-cli#96]
**Context**
Hi
I have a private network with a gasPrice null. I successfully deployed the [safe contracts](https://github.com/gnosis/safe-contracts) on it
Then I modified the contract addresses in [safe_addresses.py](https://github.com/gnosis/safe-cli/blob/master/safe_cli/safe_addresses.py)
I have been able to create a safe, informations on the safe are correctly displayed (threshold, signers, funds, etc), but I can't send funds from the safe to an another address

**Describe the bug**
I can't send funds from the safe to an another address with: `send_ether <to> <value>`

Error:
```
Traceback (most recent call last):
  File "/home/test/safe-cli/safe_cli.py", line 140, in <module>
    safe_cli.loop()
  File "/home/test/safe-cli/safe_cli.py", line 128, in loop
    self.prompt_parser.process_command(command)
  File "/home/test/safe-cli/safe_cli/prompt_parser.py", line 173, in process_command
    return args.func(args)
  File "/home/test/safe-cli/safe_cli/prompt_parser.py", line 79, in wrapper
    return function(*args, **kwargs)
  File "/home/test/safe-cli/safe_cli/prompt_parser.py", line 241, in send_ether
    safe_operator.send_ether(args.to, args.value, safe_nonce=args.safe_nonce)
  File "/home/test/safe-cli/safe_cli/safe_operator.py", line 483, in send_ether
    return self.send_custom(to, value, b"", **kwargs)
  File "/home/test/safe-cli/safe_cli/safe_operator.py", line 478, in send_custom
    return self.execute_safe_transaction(
  File "/home/test/safe-cli/safe_cli/safe_operator.py", line 761, in execute_safe_transaction
    tx_hash, tx = safe_tx.execute(
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/gnosis/safe/safe_tx.py", line 400, in execute
    self.tx_hash = self.ethereum_client.send_unsigned_transaction(
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/gnosis/eth/ethereum_client.py", line 1782, in send_unsigned_transaction
    return self.send_raw_transaction(signed_tx.rawTransaction)
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/gnosis/eth/ethereum_client.py", line 140, in with_exception_handling
    return func(*args, **kwargs)
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/gnosis/eth/ethereum_client.py", line 1731, in send_raw_transaction
    return self.w3.eth.send_raw_transaction(bytes(raw_transaction))
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/web3/eth.py", line 698, in send_raw_transaction
    return self._send_raw_transaction(transaction)
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/web3/manager.py", line 186, in request_blocking
    response = self._make_request(method, params)
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/web3/manager.py", line 147, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/web3/middleware/exception_retry_request.py", line 105, in middleware
    return make_request(method, params)
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/web3/providers/rpc.py", line 88, in make_request
    raw_response = make_post_request(
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/web3/_utils/request.py", line 49, in make_post_request
    response.raise_for_status()
  File "/home/test/safe-cli/venv/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url
```

**To Reproduce**
1. Create a private network
2. Deploy safe contracts
3. Create the safe
4. Try to transfer funds from the safe to EOA

**Comment by Uxio0** [comment]
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url

It looks like an error from the RPC. We cannot debug this issue unless you provide more data
